// import adapter from '@sveltejs/adapter-auto';
import adapter from '@sveltejs/adapter-cloudflare';
import { vitePreprocess } from '@sveltejs/vite-plugin-svelte';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	kit: {
		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
		adapter: adapter({
			// See options: https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare#options
			// Recommended for Pages to ensure all routes are handled by the SvelteKit app:
			routes: {
				include: ['/*'],
				exclude: ['<all>'] // This ensures that only files explicitly generated by SvelteKit are served, 
				                 // and Cloudflare doesn't try to serve static assets from your repo root directly.
			}
		})
	},
	preprocess: vitePreprocess(),
};

export default config;
